### ISSUE TITLE
Bug: Color scale not working in HighMaps

### ISSUE THREAD

**Issue by TheLeonKing** [kyper-data/python-highcharts#1]
I've noticed that the color scale is not working in HighMaps. This can be observed in [this notebook](http://nbviewer.jupyter.org/github/kyper-data/python-highcharts/blob/master/examples/ipynb/highmaps/Example1.ipynb), for example.

Is this a bug, or simply a missing setting?

**Comment by flyjohn02** [comment]
Hi,

Could you let me know the exact parameters (options) you input? 

Not all the parameters highchart has can be used in highmaps. It is the best to check the API document (http://api.highcharts.com/highmaps) to know what parameters are available. 

Thanks,

Hank

**Comment by TheLeonKing** [comment]
Hi John,

Thanks for your quick response. I've simply copied the example that's given in the docs (which can be found in [this Notebook](http://nbviewer.jupyter.org/github/kyper-data/python-highcharts/blob/master/examples/ipynb/highmaps/Example1.ipynb)), so I'm using the exact same parameters. But as you can see in the Notebook, the color scale is not working; it's simply white, while it should be a gradient.

Cheers,

Leon

**Comment by flyjohn02** [comment]
Hi Leon,

It might be the problem with jupyter(ipython) notebook. I got the same thing as you using ipython but made the colorAxis shown when saving as a .html file (using H.save_file()):
![chart](https://cloud.githubusercontent.com/assets/11906148/13789639/e983f69a-eb1f-11e5-9313-fb556700a910.jpeg)

Thanks for bring this problem to us. We will try look into this problem and see if there is any solution to that, but we can really not guarantee a time or anything at this time. However, I think colorAxis should work if you want to embed the map onto your webpage or other web apps.

Please let us know if you have other questions or any problems on python-highcharts.

Thanks,

Hank

**Comment by TheLeonKing** [comment]
Hi Hank,

That's remarkable indeed. But thanks for figuring out the problem!

Would it be possible to save it as an HTML file first and then embed that HTML file in iPython Notebook - as a temporary solution?

Cheers,

Leon

**Comment by flyjohn02** [comment]
Hi Leon,

Yes, you can use the display module in iPython. In fact, we also use display module to embed it, but show the chart/map directly from generated html code instead of file.

Hank

**Comment by TheLeonKing** [comment]
Hi,

I will try that then. Thanks for the help and keep up the good work! Really love this framework.

Leon
