### ISSUE TITLE
Datetime not rendered correctly

### ISSUE THREAD

**Issue by aloosley** [kyper-data/python-highcharts#13]
Thanks very much for this wrapper. 

I have been hacking around trying to get datetime to display correctly but I cannot.  Specifically, line 401 (highcharts.py)

`obj = (u"Date.UTC({year},{month},{day},{hours},{minutes},{seconds},{millisec})"`

doesn't seem to lead to the correct format being output when I provide an array of datetime objects for the x-axis.  I get outputs like "1427846400000" instead of "2014-07-01".  

Thanks and all the best.
![screen shot 2016-09-03 at 15 19 49](https://cloud.githubusercontent.com/assets/7947032/18225041/dd656b40-71e9-11e6-8d23-83cc4347b9e7.png)

**Comment by ksolan** [comment]
We just added an example with datetimes on the xAxis: http://nbviewer.jupyter.org/github/kyper-data/python-highcharts/blob/master/examples/ipynb/highcharts/spline-irregular-time.ipynb. Hopefully that helps! If not, feel free to reach out again.
