### ISSUE TITLE
Please add LICENSE to MANIFEST.in

### ISSUE THREAD

**Issue by ericdill** [kyper-data/python-highcharts#14]
The text of the MIT license requires that the license be shipped with the software.  Currently, python-highcharts is not including this license in the package.  This can be resolved by creating a MANIFEST.in file and adding LICENSE to it.  Let me know if you'd like me to submit a PR to fix this.

**Comment by flyjohn02** [comment]
plz feel free to do it.

Hank

**Comment by ksolan** [comment]
This has been addressed in the latest release (v0.3.1) -- LICENSE is included with the pypi package now. Thanks!
