### ISSUE TITLE
Heatmap like plots?

### ISSUE THREAD

**Issue by btyukodi** [kyper-data/python-highcharts#15]
I've been struggling to create the following plot:

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/maps/demo/heatmap/

but I always get an error. Does anyone have an example of how to do it? Thank you in advance!

**Comment by ksolan** [comment]
We just added a heatmap example (http://nbviewer.jupyter.org/github/kyper-data/python-highcharts/blob/v0.3.1/examples/ipynb/highcharts/heatmap.ipynb). Hopefully that should help! Let us know if you're still having trouble.

**Comment by btyukodi** [comment]
Awesome! Thanks a lot!
