### ISSUE TITLE
Adding "candlestick": (SeriesOptions, dict)->Plot options

### ISSUE THREAD

**Issue by junajo10** [kyper-data/python-highcharts#16]
class PlotOptions(BaseOptions):
    """ Another Special Case: Interface With all the different Highchart Plot Types Here """
    ALLOWED_OPTIONS = {
        "area": (SeriesOptions, dict),
        "arearange": (SeriesOptions, dict),
        "areaspline": (SeriesOptions, dict),
        "areasplinerange": (SeriesOptions, dict),
        "column": (SeriesOptions, dict),
    **"candlestick": (SeriesOptions, dict),**
        "columnrange": (SeriesOptions, dict),
        "flags": (SeriesOptions, dict),
        "line": (SeriesOptions, dict),
        "ohlc": (SeriesOptions, dict),
        "polygon": (SeriesOptions, dict),
        "scatter": (SeriesOptions, dict),
        "series": (SeriesOptions, dict),
        "spline": (SeriesOptions, dict),
    }

**Comment by ksolan** [comment]
Added in our new release (v0.3.1). Thanks!
