### ISSUE TITLE
Column stacked and grouped not working 

### ISSUE THREAD

**Issue by araichev** [kyper-data/python-highcharts#17]
Hi there,

I can't reproduce in my Python 3.5 Jupyter Notebook your column-stacked-and-grouped example.
In particular, the grouping isn't working.
Here is a screenshot.

<img width="351" alt="screen shot 2016-10-28 at 18 51 27" src="https://cloud.githubusercontent.com/assets/4087432/19796321/fac12f5e-9d3f-11e6-8367-23d577309b69.png">

**Comment by ksolan** [comment]
This was a bug on our end that was fixed in v0.3.1. Thanks for bringing it to our attention!
