### ISSUE TITLE
Scatter point name

### ISSUE THREAD

**Issue by ayamahmod** [kyper-data/python-highcharts#3]
How can I add a variable name for each point in a scatter plot ?

**Comment by flyjohn02** [comment]
Hi Aya,

Could you be more specific? The example: http://www.highcharts.com/demo/scatter shows the variable name on tooltip. Is it what you need?

**Comment by ayamahmod** [comment]
Yes. In this example, it shows the x, and y dimensions of each point. I'd like to show something else for each point.
For example, each point will be (x,y,z)
x,y specify its location, and z specifies its name.

**Comment by flyjohn02** [comment]
Hi Aya,

Please check the way the format of data object for scatter plot: http://api.highcharts.com/highcharts#series<scatter>.data. You may form your data object in the way like: data: [{
    x: 1,
    y: 2,
    z: "Point2",
    color: "#00FF00"
}, {
    x: 1,
    y: 4,
    z: "Point1",
    color: "#FF00FF"
},.....]
and in the tooltip of option object, you may do : 'tooltip': {
            'pointFormat': '{point.x}, {point.y}, {point.z}'
}

Hope this helps. 

Hank

**Comment by ayamahmod** [comment]
I formatted the data object in this way:
Data=[]
for i in range(1:10):
Data.append({'x': i, 'y': i, 'z': str(i)})
, added this object using add_data_set
H.add_data_set(Data, 'scatter', 'Customers', color='rgba(223, 83, 83, .5)')
, and formatted the tooltip of option object the way you said.
But nothing was drawn, The graph doesn't have any points.

**Comment by flyjohn02** [comment]
Hi Aya,

I am not sure why this doesn't work for you. I tried it and got: 

<img width="1095" alt="screen shot 2016-03-19 at 11 24 49 pm" src="https://cloud.githubusercontent.com/assets/11906148/13899472/ee5f3794-ee29-11e5-9875-13ff99e7f1ff.png">

Here is my code (ipython): 
```
# -*- coding: utf-8 -*-
from highcharts import Highchart
H = Highchart(width=850, height=400)

options = {
	'chart': {
        'type': 'scatter',
        'zoomType': 'xy'
    },
    'legend': {
        'layout': 'vertical',
        'align': 'left',
        'verticalAlign': 'top',
        'x': 100,
        'y': 70,
        'floating': True,
        'backgroundColor': "(Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'",
        'borderWidth': 1
    },
    'plotOptions': {
        'scatter': {
            'tooltip': {
                'headerFormat': '<b>{series.name}</b><br>',
                'pointFormat': '{point.x}, {point.y}, {point.z}'
            }}},}
data = []
for i in range(1,10):
    data.append({'x': i, 'y': i, 'z': str(i)})

H.set_dict_options(options)
H.add_data_set(data, 'scatter', 'Customers', color='rgba(223, 83, 83, .5)')
H
```

btw, I noticed you have `range(1:10)` which is not allowed in python. Can you check if it is the problem?

**Comment by ayamahmod** [comment]
It works well with around 1000 points, when I expand my dataset to more than 300,000 points, it plots nothing.

**Comment by flyjohn02** [comment]
Hi Aya,

Please change your [turboThreshold](http://api.highcharts.com/highcharts#series<scatter>.turboThreshold) setting (to the number you need) in add_data_set function. I tried 300,000 and it works:

<img width="1103" alt="screen shot 2016-03-20 at 1 07 28 am" src="https://cloud.githubusercontent.com/assets/11906148/13900058/55e2e04c-ee38-11e5-9b04-44b7f2e02e2e.png">

However, it will be slow because of lots of data points. I may not recommend to show each data point on tooltip. 

Hope this helps

**Comment by ayamahmod** [comment]
It worked finally! Thank you for your fast reply.
