### ISSUE TITLE
Unable to plot use python-highcharts

### ISSUE THREAD

**Issue by shenweima** [kyper-data/python-highcharts#63]
I had a web app using python-highcharts, it worked well until the last two days. 
It is unable to plot chart.
This is [my website](http://202.194.139.32/expression/index.html), we can input " TraesCS3B02G323400" for test. 
This is my [code](https://github.com/shenweima/python-web-expression/blob/master/gene_expression_new.py)。
[TraesCS3B02G323400](http://202.194.139.32/cgi-bin/gene_expression.py?expressiontable=PRJNA243835_stripe_tbl&ID=TraesCS3B02G323400)

**Comment by Gnommer** [comment]
I also have similar issues like i have written a wrapper on it. it worked fine untill last two days the graphs stopped rendering

**Comment by ksolan** [comment]
Hi,

Thanks for reporting. This has been fixed by #62, which was just released as v0.4.2.
