### ISSUE TITLE
Not rendering charts

### ISSUE THREAD

**Issue by carlskii** [kyper-data/python-highcharts#7]
Hi,

Excellent work here. However, event though 'python-highcharts' installed OK, my charts are not rendering. 

There are some errors in the console output: 

```
[IPKernelApp] ERROR | No such comm target registered: ipython.widget
[W 16:13:46.389 NotebookApp] 404 GET /api/kernels/66a4092a-4ea4-4b57-99da-60982c7d56bf/channels?session_id=15B39D0998384375969F9ED94E6EA5D2 (127.0.0.1): Kernel does not exist: 66a4092a-4ea4-4b57-99da-60982c7d56bf
[W 16:13:46.398 NotebookApp] 404 GET /api/kernels/66a4092a-4ea4-4b57-99da-60982c7d56bf/channels?session_id=15B39D0998384375969F9ED94E6EA5D2 (127.0.0.1) 10.93ms referer=None
```

 Any ideas where I should look ? 

Thanks.

**Comment by flyjohn02** [comment]
Hi,

It seems to me that it is due to setting in the environment: https://github.com/jupyter/notebook/issues/397 Could you check it first and see if it fixes that problem? Please feel free to let us know if not.

Hank
